In [15]:
import pandas as pd

In [16]:
df=pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
#Task 2(Exploration of dataset)

print(f"number of rows:{df.shape[0]}")
print(f"number of columns:{df.shape[1]}")

print(f"\nData types of each column:\n{df.dtypes}")
print(f"\nMissing values:\n{df.isnull().sum()}")

print("\nNumerical features:")
numerical=df.select_dtypes(include=['int64','float64']).columns.tolist()
print(numerical)

print("\nCategorical features:")
categorical=df.select_dtypes(include=['object', 'str']).columns.tolist()
print(categorical)

number of rows:891
number of columns:12

Data types of each column:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Numerical features:
['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

Categorical features:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [18]:
#Task 3 (Data Cleaning)
#task D - remove rows with missing values

print("Missing values before cleaning:")
print(df.isnull().sum())
print(f"Total rows before cleaning: {df.shape[0]}")
rows_before=df.shape[0]

#removing irrelevant columns
df=df.drop(columns=['Name', 'Ticket', 'Cabin'])
print("\nIrrelevant columns removed: Name, Ticket, Cabin")

#Removing rows with missing values
df=df.dropna()

print("\nMissing values after cleaning:")
print(df.isnull().sum())
rows_after=df.shape[0]

print(f"\nTotal rows after cleaning:{rows_after}")
print(f"\nRows removed:{rows_before - rows_after}")

Missing values before cleaning:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
Total rows before cleaning: 891

Irrelevant columns removed: Name, Ticket, Cabin

Missing values after cleaning:
PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

Total rows after cleaning:712

Rows removed:179

In [19]:
#Task 4 (Data transformation)

df['Sex']=df['Sex'].map({'male':0, 'female':1})
df['Embarked']=df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})
print(df.dtypes)
df.head(10)

PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object

    PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0             1         0       3    0  22.0      1      0   7.2500         0
1             2         1       1    1  38.0      1      0  71.2833         1
2             3         1       3    1  26.0      0      0   7.9250         0
3             4         1       1    1  35.0      1      0  53.1000         0
4             5         0       3    0  35.0      0      0   8.0500         0
6             7         0       1    0  54.0      0      0  51.8625         0
7             8         0       3    0   2.0      3      1  21.0750         0
8             9         1       3    1  27.0      0      2  11.1333         0
9            10         1       2    1  14.0      1      0  30.0708         1
10           11         1       3    1   4.0      1      1  16.7000         0

In [20]:
#Task 5 (Feature Selection)
 
y=df['Survived']
print("Target variable: Survived")
print(y.value_counts())
print("\n0 is did not survived\n1 is survived")

#select at least 4 features
X=df[['Pclass', 'Sex', 'Age', 'Fare']]
print(f"\nSelected Features: \n{X.head()}")

Target variable: Survived
Survived
0    424
1    288
Name: count, dtype: int64

0 is did not survived
1 is survived

Selected Features:
   Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

Selected features:

Pclass - passenger class affects survival

Sex - strong correlation with survival

Age - age impacts survival probability

Fare - reflects socio-economic status

In [21]:
#Task 6(Final Dataset)

print("Missing values in final dataset:")
print(df.isnull().sum())
print(f"Total missing values: {df.isnull().sum().sum()}")

print(f"\nData types of final dataset: \n{df.dtypes}")

print(f"\nFinal dataset size: {df.shape[0]} rows, {df.shape[1]} features")
print(f"Final dataset: \n{df.head()}")

Missing values in final dataset:
PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64
Total missing values: 0

Data types of final dataset:
PassengerId      int64
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object

Final dataset size: 712 rows, 9 features
Final dataset:
   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    0  22.0      1      0   7.2500         0
1            2         1       1    1  38.0      1      0  71.2833         1
2            3         1       3    1  26.0      0      0   7.9250         0
3            4         1       1    1  35.0      1      0  53.1000         0
4            5         0       3    0  35.0      0      0   8.0500         0

## Task 7. Conclusion
In conclusion, the most challenging part of this assignment was handling missing values, because removing rows can reduce the size of the dataset and potentially affect the quality of analysis.

During this work, I completed key steps of the machine learning workflow: loading the dataset, exploring its structure, identifying missing values, cleaning the data by removing incomplete rows, transforming categorical features into numerical format, and selecting relevant features for the model.

After cleaning, the dataset contains no missing values and all features are in numerical format, which makes it suitable for machine learning algorithms.

Therefore, the dataset is fully prepared and ready for further model training.